# Generated by Django 4.1.11 on 2023-09-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertybkp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
